import org.optaplanner.examples.cloudbalancing.domain.CloudBalance;
import org.optaplanner.examples.cloudbalancing.domain.CloudComputer;
import org.optaplanner.examples.cloudbalancing.domain.CloudProcess;
import org.optaplanner.examples.cloudbalancing.GroupKey;

rule R1 when
    CloudProcess($key: computer)
    not( GroupKey(key == $key) )
then
    insert( new GroupKey( $key ) );
end

rule R2 when
    $k: GroupKey( $key : key )
    not( CloudProcess( computer == $key ) )
then
    delete ( $k );
end

rule R3 when
    GroupKey( $computer : key )
    accumulate (
        CloudProcess( $requirement: requiredCpuPower, computer == $computer );
                $sum : sum($requirement);
                $sum > ((CloudComputer)$computer).getCpuPower()
    )
then
    // Dummy operation
end
